steps:

  # Install pipeline requirements
  - name: "python:3.10"
    id: "pipeline-init"
    entrypoint: "pip3"
    args: ["install", "-r", "requirements.txt", "--user"]
    dir: 'pipelines/{{cookiecutter['pipeline_name']}}'

  - name: "python:3.10"
    id: "pipeline-build"
    entrypoint: bash
    args:
      - '-c'
      - |
        branch_name=$BRANCH_NAME
        branch=${branch_name//\//-}
        python pipeline.py --project ${_PROJECT_ID} --region ${_REGION} --pipeline-name {{cookiecutter['pipeline_name']}} --pipeline-file /workspace/pipeline.yaml --artifact-registry-url ${_ARTIFACT_REGISTRY_TEMPLATES_URL} -t latest $SHORT_SHA $branch
    dir: 'pipelines/{{cookiecutter['pipeline_name']}}'
