openapi: 3.0.2
info:
  title: API
  description: API to retrieve information about the speaker
  version: 1.0.0
servers:
  - url: 'https://ab-test-service.ab-service-dir.example.com'
paths:
  /speaker:
    post:
      summary: >
        Get speaker bio, and the title of the topic that he will present and its
        description
      operationId: Speaker Information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: The identifier of the speaker
                  example: "speaker-id-123"
      responses:
        '200':
          description: Speaker Information
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: Name of the speaker
                        company:
                          type: string
                          description: Company the speaker represents
                        image:
                          type: string
                          description: URL of the speaker's image
                        bio:
                          type: string
                          description: Speaker bio
                        time:
                          type: string
                          format: time
                          description: Time of the speaker's talk
                        day:
                          type: string
                          format: date
                          description: Day of the speaker's talk
                        topic:
                          type: string
                          description: Title of the talk
                        position:
                          type: number
                          description: Position of the talk in the event schedule
                        topic_summary:
                          type: string
                          description: Summary of the topic
                        venue:
                          type: string
                          description: Venue where the talk will be held
                        bq_datetime:
                          type: string
                          format: date-time
                          description: Datetime of the talk in the format YYYY-MM-DD HH:mm:ss
        '400':
          description: Bad request - Invalid query parameter or missing required parameter
        '404':
          description: Speaker not found
