steps:

  - name: "gcr.io/cloud-builders/docker"
    dir: "${_PROJECT_ROOT}/components/{{cookiecutter['component_name']}}"
    entrypoint: bash
    args:
      - "-c"
      - |
        branch_name=$BRANCH_NAME
        branch=${branch_name//\//-}
        docker build -t {{cookiecutter['image_dest']}}:latest -t {{cookiecutter['image_dest']}}:$SHORT_SHA -t {{cookiecutter['image_dest']}}:$branch --network=cloudbuild .

  - name: 'gcr.io/cloud-builders/docker'
    dir: "${_PROJECT_ROOT}/components/{{cookiecutter['component_name']}}"
    entrypoint: docker
    args: [
      "push",
      "-a",
      "{{cookiecutter['image_dest']}}",
    ]
